version: '2'

#  
#  Copyright © 2024 Mohammad Wildan Nuryulda
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

services:
  ZK731:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: ZK731
    network_mode: "host"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ../data/zookeeper/zk-data:/var/lib/zookeeper/data
      - ../data/zookeeper/zk-txn-logs:/var/lib/zookeeper/log
      - ../jaas:/etc/kafka/jaas
      - ../ssl-wilcard:/etc/kafka/secrets
    environment:
      # =================================  ZOOKEEPER  =================================
      # -> general config zookeeper
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SECURE_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 12000
      ZOOKEEPER_INIT_LIMIT: 15
      ZOOKEEPER_SYNC_LIMIT: 10
      ZOOKEEPER_MAX_CLIENT_CNXNS: 0

      # -> log
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "INFO"

      # -> zookeeper servers
      #ZOOKEEPER_SERVERS: x:2888:3888;x:2888:3888;x:2888:3888

      # -> ssl zookeeper
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      ZOOKEEPER_SSL_CLIENT_AUTH: none

      # -> ssl zookeeper quorum
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD: confluent

      # -> sasl zookeeper
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_AUTH_PROVIDER_X509: org.apache.zookeeper.server.auth.X509AuthenticationProvider

      # -> jmx port
      KAFKA_JMX_PORT: 9581

      # -> timezone
      TZ: Asia/Jakarta

      # other zookeeper stuff
      KAFKA_HEAP_OPTS: -Xms1G
      KAFKA_OPTS: -Dzookeeper.4lw.commands.whitelist=*
                  -Djava.security.auth.login.config=/etc/kafka/jaas/zookeeper_server_jaas.conf





  BK731:
    image: confluentinc/cp-server:7.3.1
    container_name: BK731
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ../data/broker/kafka-data:/var/lib/kafka/data
      - ../jaas:/etc/kafka/jaas
      - ../helper:/etc/kafka/helper
      - ../ssl-wilcard:/etc/kafka/secrets
    environment:
      # ================================= BROKER =================================
      # -> general config
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: R1

      # -> listeners broker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL
      KAFKA_LISTENERS: PLAINTEXT://<host>:9092,SSL://<host>:9093,SASL_SSL://<host>:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<host>:9092,SSL://<host>:9093,SASL_SSL://<host>:9094

      # -> zookeeper connection
      KAFKA_ZOOKEEPER_CONNECT: <host>:2182
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 120000

      # -> zookeeper connection ssl
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS

      # -> acl
      KAFKA_ZOOKEEPER_SET_ACL: 'true'
      KAFKA_ZOOKEEPER_SASL_ENABLED: "true"
      KAFKA_SUPER_USERS: User:admin;User:ANONYMOUS;User:client
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'

      # -> configure sasl-scram
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512

      # -> ssl broker
      KAFKA_SSL_KEYSTORE_FILENAME: <name_of>.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: cert_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: <name_of>.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: cert_creds
      KAFKA_SSL_KEY_CREDENTIALS: cert_creds

      # -> metrics reporter
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'

      # -> metrics reporter using ssl
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: <host>:9094
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_SSL
      CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
              username=\"admin\" \
              password=\"confluent\";"

      CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: SCRAM-SHA-512
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEY_PASSWORD: confluent

      # -> components partitions and impersonation broker
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # -> auto create topic
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      # -> log
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO,kafka.controller=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # -> disable auto-enable telemetry
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: 'false'

      # -> disable self balancing
      KAFKA_CONFLUENT_BALANCER_ENABLE: 'false'

      # -> disable health plus
      CONFLUENT_TELEMETRY_ENABLED: 'false'

      # -> jmx port
      KAFKA_JMX_PORT: 9582

      # -> timezone
      TZ: Asia/Jakarta

      # -> other broker stuff
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_HEAP_OPTS: -Xms1G
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas/broker_server_jaas.conf
                  -Dzookeeper.client.secure=true
                  -Dzookeeper.ssl.keyStore.location=/etc/kafka/secrets/<name_of>.keystore.jks
                  -Dzookeeper.ssl.keyStore.password=confluent
                  -Dzookeeper.ssl.trustStore.location=/etc/kafka/secrets/<name_of>.truststore.jks
                  -Dzookeeper.ssl.trustStore.password=confluent


  SR731:
    image: confluentinc/cp-schema-registry:7.3.1
    container_name: SR731
	restart: unless-stopped
    network_mode: "host"
    volumes:
      - ../ssl-wilcard:/etc/kafka/secrets
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      # ======================= SCHEMA REGISTRY =======================
      # -> general config schema-registry
      SCHEMA_REGISTRY_HOST_NAME: <host>
      SCHEMA_REGISTRY_LISTENERS: http://<host>:8081,https://<host>:8082
      SCHEMA_REGISTRY_DEBUG: 'true'
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: https
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_SSL://<host>:9094

      # -> schema compability [ backward, backward_transitive, forward, forward_transitive, full, full_transitife, none]
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: backward_transitive

      # -> log
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO

      # -> schema-registry connect to broker
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: SCRAM-SHA-512
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
              username=\"client\" \
              password=\"confluent\";"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: confluent

      # -> ssl schema-registry https end-point
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks

      # -> timezone
      TZ: Asia/Jakarta

      # -> other schema registry stuff
      SCHEMA_REGISTRY_OPTS: -Xmx1G



  C3731:
    image: confluentinc/cp-enterprise-control-center:7.3.1
    container_name: C3731
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ../ssl-wilcard:/etc/kafka/secrets
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      # ======================= CONFLUENT CONTROL CENTER (C3) =======================
      # -> general configs

      CONTROL_CENTER_BOOTSTRAP_SERVERS: <host>:9094
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_STREAMS_SASL_MECHANISM: SCRAM-SHA-512
      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
              username=\"client\" \
              password=\"confluent\";"

      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 2
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 2
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONFLUENT_METRICS_TOPIC_PARTITIONS: 2

      # -> amount of heap to use for internal caches for increase for better throughput
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 100000000
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1

      # -> ssl config for streams control center
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_PASSWORD: confluent
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_PASSWORD: confluent
      CONTROL_CENTER_STREAMS_SSL_KEY_PASSWORD: confluent

      # -> logs
      CONTROL_CENTER_LOG4J_ROOT_LOGLEVEL: 'INFO'
      CONTROL_CENTER_CONTROL_CENTER_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONTROL_CENTER_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      CONTROL_CENTER_CONTROL_CENTER_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'

      # -> listener config for http and https control center ui
      CONTROL_CENTER_REST_LISTENERS: http://<host>:9021,https://<host>:9022
      PORT: 9021
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/<name_of>.truststore.jks
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_PASSWORD: confluent
      CONTROL_CENTER_REST_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/<name_of>.keystore.jks
      CONTROL_CENTER_REST_SSL_KEYSTORE_PASSWORD: confluent
      CONTROL_CENTER_REST_SSL_KEY_PASSWORD: confluent

      # -> components module of confluent kafka cluster
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://<host>:8081,https://<host>:8082

      # -> other control center stuff
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: 'false'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CONTROL_CENTER_HEAP_OPTS: -Xmx4g


